config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friendships, only: [:create, :destroy]
  resources :user_stocks, only: [:create, :destroy]

    root to: 'welcome#index'
    get 'my_portfolio', to: 'users#my_portfolio'
    get 'search_stock', to: 'stocks#search'
    get 'my_friends', to: 'users#my_friends'
    get 'search_friends', to: 'users#search'
  resources :users, only: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord

  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true





  def self.new_lookup(ticker_symbol)
        client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
      endpoint: 'https://sandbox.iexapis.com/v1'
    )

    begin
      return Stock.new(ticker: ticker_symbol.upcase, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
    rescue
      return nil
    end
  end

  def self.check_db(ticker_symbol)
    return Stock.where(ticker:ticker_symbol).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def already_tracking?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    if stock
      return stocks.where(id:stock.id).exists?
    else
      return false
    end
  end

  def under_ten?
    stocks.count <10
  end


  def can_track_stock?(ticker_symbol)
    if under_ten? && !already_tracking?(ticker_symbol)

      return true
    end
  end

  def full_name
    if first_name || last_name
      "#{first_name} #{last_name}"
    else
      "Anonymous"
    end
  end

  def exclude_current_user(array)
    return array.reject{|user| user.id == self.id}
  end

  def self.search(params)
    params.strip!
    search_results = (User.email_search(params) + User.first_name_search(params) + User.last_name_search(params)).uniq
    if search_results
      return search_results
    else
      return nil
    end
  end

  def self.email_search(query)
    return User.match("email", query)
  end

  def self.first_name_search(query)
    return User.match("first_name", query)
  end

  def self.last_name_search(query)
    return User.match("last_name", query)
  end

  def self.match(field_name,query)
    return User.where("#{field_name} like ?", "%#{query}%")
  end

  def already_following?(friend_id)
    return self.friends.where(id: friend_id).exists?
  end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    want_to_follow = User.find(params[:id])
    current_user.friendships.build(friend_id: want_to_follow.id)
    if current_user.save
      flash[:notice] ="Following #{want_to_follow.full_name}"
    else
      flash[:alert] = "There was a problem"
    end
    redirect_to my_friends_path
  end

  def destroy
    friendship_to_kill = User.find(params[:id])
    Friendship.where(user_id: current_user.id, friend_id: friendship_to_kill.id).first.destroy
    flash[:notice] ="Successfully unfollowed #{friendship_to_kill.full_name}"
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock != nil
        respond_to do |format|
          format.js{render partial: 'users/results.js.erb'}
        end

      else
        respond_to do |format|
          flash.now[:alert] = "Please enter a valid ticker symbol"
          format.js{render partial: "users/results.js.erb"}
        end

      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a ticker symbol"
        format.js{render partial: "users/results.js.erb"}
      end
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
    stock = Stock.new_lookup(params[:ticker])
    stock.save
    end
    @user_stock = UserStock.create(user: current_user,stock: stock)
    flash[:notice]="You have successfully added #{stock.ticker} to your portfolio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock_to_kill = Stock.find(params[:id])
    UserStock.where(user_id: current_user.id, stock_id: stock_to_kill.id).first.destroy
    flash[:notice] ="Successfully removed #{stock_to_kill.ticker}"
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @tracked_stocks = current_user.stocks
    @user = current_user
  end

  def my_friends
    @following = current_user.friends
  end

  def search
    if params[:query].present?
      @query_results = User.search(params[:query])
      @query_results = current_user.exclude_current_user(@query_results)
      if @query_results
        respond_to do |format|
          format.js{render partial: 'users/friend_results.js.erb'}
        end

      else
        respond_to do |format|
          flash.now[:alert] = "No such potential friend exists"
          format.js{render partial: "users/friend_results.js.erb"}
        end

      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a name or email"
        format.js{render partial: "users/friend_results.js.erb"}
      end
    end
  end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_list_friends.html.erb
<div class="row p-5">
  <table class="table table-hover">
    <thead class="thead-dark">
      <tr>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Email</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @following.each do |f| %>
      <tr>
        <th scope="row"><%= f.first_name%></th>
        <td><%= f.last_name%></td>
        <td><%= f.email%></td>
        <td><%= link_to 'View profile',user_path(f), class: "btn btn-sm btn-primary"%>
        <%= link_to 'Stop following',friendship_path(f), method: :delete, class: "btn btn-sm btn-danger"%></td>
      </tr>
      <% end %>

    </tbody>
  </table>
</div>

app/views/layouts/_messages.html.erb
<% if notice %>
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <p><%= notice %></p>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

<% if alert %>

<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <p><%= alert %></p>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
 <% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">


  <%= link_to 'StockTracker', root_path, class:"navbar-brand font-weight-bold" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
<% if current_user %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
          <%= link_to 'My Portfolio', my_portfolio_path, class:"nav-link" %>
      </li>
      <li class="nav-item">

        <%= link_to 'My Friends', my_friends_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profile
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

          <%= link_to edit_user_registration_path, class:"dropdown-item" do %>
            <%= fa_icon 'edit' %>
            <%="Edit profile" %>
          <% end %>
          
          </div>
      </li>
    
    </ul>
    <ul class="navbar-nav mr-1">
      <li class="nav-item navbar-text mr-2 font-weight-bold">
        <%= fa_icon 'user' %>
        <%= current_user.full_name %>
      </li>
      <li class="nav-item">
      <%= link_to 'Logout',destroy_user_session_path, method: :delete, class:"btn btn-outline-danger" %>
    </li>
    </ul>
   
  </div>
<% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar.html.erb" %>
    <div class="container">
    <%= render "layouts/messages.html.erb" %>

    <%= yield %>

    </div>
  </body>
</html>

app/views/stocks/_list_stocks.html.erb
<div class="row p-5">
  <table class="table table-hover">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Ticker</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @tracked_stocks.each do |ts| %>
        <tr>
          <th scope="row"><%= ts.ticker%></th>
          <td><%= ts.name%></td>
          <td><%= ts.last_price%></td>
          <td>
            <% if current_user.can_track_stock?(ts.ticker) %>
              <div class="card-body row p-2">
                <%= link_to 'Add to Portfolio', user_stocks_path(user:current_user,ticker:ts.ticker), class:"btn btn-primary", method: :post%>
              </div>
            <% elsif current_user.id != @user.id %>
              <div class="card-body row p-2">
                <p>You are already tracking
                  <% if !current_user.under_ten? %>
                    10 stocks
                    <% elsif current_user.already_tracking?(ts.ticker)%>
                      <strong><%= ts.ticker %></strong>
                    <% end %>
                  </p>
                </div>
              <% end %>


            <% if current_user.id == @user.id %>

              <%= link_to 'Remove', user_stock_path(ts), method: :delete, data: {confirm: "are you sure?"},class: "btn btn-sm btn-danger"%>

            <% end %>
</td>
          </tr>
        <% end %>

      </tbody>
    </table>
  </div>

app/views/users/_friend_results.html.erb
<% if @f %>
  <div class="card col-5 bg-light">
    <div class="card-body row p-2">
      <p class="card-text font-weight-bold">Symbol:
      </p>
      <%= @f %>
    </div>
    <div class="card-body row p-2">
      <p class="card-text font-weight-bold">Name:
      </p><%= @f %>
    </div>
    <div class="card-body row p-2">
      <p class="card-text font-weight-bold">Last Price:
      </p><%= @f %>
    </div>
      <div class="card-body row p-2">
        <%= link_to 'Follow friend', '#', class:"btn btn-primary", method: :post%>
      </div>
    <div class="card-body row p-2">
      <p>You are already tracking

      </p>
    </div>


    </div>
  <% else %>
    <div class="col-3 p-0">
      <%= render "layouts/messages.html.erb"%>
    </div>

  <% end %>

app/views/users/_friend_results.js.erb
document.getElementById("friend-results").innerHTML= "<%= escape_javascript(render 'users/friend_results.html.erb') %>"

app/views/users/_results.html.erb
<% if @stock %>
  <div class="card col-5 bg-light">
    <div class="card-body row p-2">
      <p class="card-text font-weight-bold">Symbol:
      </p>
      <%= @stock.ticker %>
    </div>
    <div class="card-body row p-2">
      <p class="card-text font-weight-bold">Name:
      </p><%= @stock.name %>
    </div>
    <div class="card-body row p-2">
      <p class="card-text font-weight-bold">Last Price:
      </p><%= @stock.last_price %>
    </div>
    <% if current_user.can_track_stock?(@stock.ticker) %>
      <div class="card-body row p-2">
        <%= link_to 'Add to Portfolio', user_stocks_path(user:current_user,ticker:@stock.ticker), class:"btn btn-primary", method: :post%>
      </div>
    <% else %>
    <div class="card-body row p-2">
      <p>You are already tracking
      <% if !current_user.under_ten? %>
        10 stocks
      <% elsif current_user.already_tracking?(@stock.ticker)%>
        <strong><%= @stock.ticker %></strong>
      <% end %>
      </p>
    </div>
    <% end %>

    </div>
  <% else %>
    <div class="col-3 p-0">
      <%= render "layouts/messages.html.erb"%>
    </div>

  <% end %>

app/views/users/_results.js.erb
document.getElementById("results").innerHTML="<%= escape_javascript(render 'users/results.html.erb') %> "

app/views/users/my_friends.html.erb
<h1>My Friends</h1>

<div class="search-area">
  <h3>Search friends</h3>

  <%= form_tag search_friends_path, remote: true, method: :get do %>
  <div class="form-group row">
    <div class="col-3">
      <%= text_field_tag :query, params[:query], placeholder: "Name or email", autofocus: true, class: "form-control"%>
    </div>
    <div>
      <%= button_tag type: :submit, class: "btn btn-primary" do%>
      <%= fa_icon "search"%>
    <% end %>
  </div>
</div>
<% end %>

</div>

<div id="friend-results">

</div>

<% if @following.present? %>
<%= render 'friends/list_friends.html.erb'%>

<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>
<div class="search-area">
  <h3>Search stocks</h3>

  <%= form_tag search_stock_path, remote: true, method: :get do %>
  <div class="form-group row">
    <div class="col-3">
      <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control"%>
    </div>
    <div>
      <%= button_tag type: :submit, class: "btn btn-primary" do%>
      <%= fa_icon "search"%>
    <% end %>
  </div>
</div>
<% end %>

</div>

<div id="results">

</div>

<% if @tracked_stocks.present? %>
<%= render 'stocks/list_stocks.html.erb'%>

<% end %>

app/views/users/show.html.erb
    <div class="card col-5 mb-2 bg-light">

      <div class="card-body row p-2">
        <p class="card-text font-weight-bold">Name:
        </p>
        <%= @user.full_name %>
      </div>
      <div class="card-body row p-2">
        <p class="card-text font-weight-bold">Email:
        </p><%= @user.email %>
      </div>
      <div class="card-body row p-2">


      </div>
      <% if current_user.already_following?(@user.id)%>
        <p class="font-weight-bold">You are already following</p>
      <% else %>
        <div class="card-body row p-2">
          <%= link_to 'Follow friend', friendships_path(id: @user.id), class:"btn btn-outline-primary", method: :post%>
        </div>
      <% end %>

    </div>

  <div class="col-5 p-0">
    <%= render "layouts/messages.html.erb"%>
  </div>

  <% if @tracked_stocks.present? %>
  <%= render 'stocks/list_stocks.html.erb'%>
  <% else %>
  <p>This user is not tracking any stocks</p>

  <% end %>

app/views/welcome/index.html.erb
<h1>Welcome to StockTracker!</h1>

<%= link_to 'Sign out', destroy_user_session_path, method: :delete %>